### ISSUE TITLE
运行起来，但是Whitelabel Error Page

### ISSUE THREAD

**Issue by dyf505776897** [sail-y/spring-boot-admin#1]
http://localhost:10000
结果是：
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Mar 01 17:29:55 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by sail-y** [comment]
试试看这个地址：

http://localhost:10000/web/views/login/login.html

**Comment by xiongleio** [comment]
导入idea一直报错

**Comment by sail-y** [comment]
什么错？

**Comment by xyimatvoid** [comment]
pom文件，<parent>
		<groupId>com.bbd</groupId>
		<artifactId>xloan-parent</artifactId>
		<version>0.1.0-SNAPSHOT</version>
	         </parent>
找不到，下面的依赖库找不到。

**Comment by luyaozhang** [comment]
pom文件，
com.bbd
xloan-parent
0.1.0-SNAPSHOT

这个我也找不到，求指点

**Comment by sail-y** [comment]
抱歉各位，疏忽了，我重新推了代码，改了一下依赖
