### ISSUE TITLE
jar 方式运行，页面404

### ISSUE THREAD

**Issue by Andyfan322** [sail-y/spring-boot-admin#5]
jar 方式运行，页面404

**Comment by sail-y** [comment]
http://localhost:10000/web/views/login/login.html

也提示404？

**Comment by Andyfan322** [comment]
导致404问题查找到了，idea本地运行路径配置忽略大小写，jar方式运行不行。另外还有个循环依赖问题，题主可以试试，也是jar方式运行。将` @Bean
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        // This method is here with the @Bean annotation so that Spring can
        // autowire it
        return super.authenticationManagerBean();
    }`
放到WebSecurityConfig ，解决了！

**Comment by sail-y** [comment]
我记得我没遇到过你说的问题啊，我有个项目都用jar部署到生产的呢
