### ISSUE TITLE
新添加页面，沿用样式

### ISSUE THREAD

**Issue by Jiaozi97** [sail-y/spring-boot-admin#6]
![QQ截图20190417190405](https://user-images.githubusercontent.com/36891136/56283308-eee1f680-6143-11e9-9a8f-b526d9b51d97.png)
您好！请问在新建的菜单，及其新建的功能如何按您的css的样式增添html？
1.我把您user下的html js css都拷贝到新文件夹"a"，将user.html改名为a.html，并在资源管理内设置了新功能的路径../a/a.html。
2.运行新建的功能，显示html内的“用户名 | 昵称 | 创建时间 |  操作”，没有bootstrap格式（因为套用您的html，bootstrap文件的路径，及html中引用路径没有修改）；显示"确定"button，其他样式不能显示。

【暂时页面显示正常了，暂时保留该问题，这是个什么神奇的情况？】
关于恢复正常以后：
1.想问问您是用jsp而没用用其他模板引擎么？
2.作为jsp初学者，请问如何自己搭建一个新的页面？
3.如果用thymeleaf可以和资源管理对接上么？

后端学习中，前端知识了解太少，还望您多多包涵！

**Comment by sail-y** [comment]
这里面是代码都是前后端分离的。前端是用的backbone.js和bootstrap做的，纯html页面，你如果要用thymeleaf，无非就是有些参数，可以通过后端传入前端，不通过接口，由服务器来渲染页面。

**Comment by Jiaozi97** [comment]
好的感谢！正在用thymeleaf。
我现在按照绝对路径的格式../templates/list.html，给一个新功能增加了页面，
但页面上我的一个“<a href="/toAdd" th:href="@{/toAdd}" class="btn btn-info">add</a>”被告知没有权限，只是一个页面的跳转，应该如何增加到您的权限管理中去呢？

**Comment by sail-y** [comment]
这种你可能得自己改造一下权限的设计结构了，因为是前后端分离的项目，项目里只做了对接口类型的路径的判断，你可以看看代码和数据表的结构
